"""
Generate a synthetic MATH training dataset from templates. No AI involved:
every problem is generated by plain Python arithmetic, so every answer is
guaranteed correct.

Covers: addition, subtraction, multiplication, division, squares,
comparisons, and simple word problems — each with a short worked step so
the model learns to SHOW the calculation, not just emit a number.

HONESTY NOTE: a small model learns arithmetic as a pattern, not as an
algorithm. It will get small numbers mostly right and large numbers wrong.
Real calculator-grade math at any model size is done by letting the app
detect math and compute it in code (see chat/calculator hook) — which is
how real assistants do it too.

Run: python -m my_ai.data.make_math_data
Writes: my_ai/data/raw/math_synthetic.jsonl
"""
from __future__ import annotations

import json
import os
import random

Q_ADD = ["What is {a} plus {b}?", "What is {a} + {b}?", "Add {a} and {b}.",
         "Calculate {a} + {b}.", "How much is {a} plus {b}?", "{a} + {b} = ?"]
Q_SUB = ["What is {a} minus {b}?", "What is {a} - {b}?", "Subtract {b} from {a}.",
         "Calculate {a} - {b}.", "How much is {a} minus {b}?"]
Q_MUL = ["What is {a} times {b}?", "What is {a} x {b}?", "Multiply {a} by {b}.",
         "Calculate {a} times {b}.", "How much is {a} times {b}?"]
Q_DIV = ["What is {a} divided by {b}?", "Divide {a} by {b}.", "Calculate {a} / {b}."]

WORD_ADD = [
    ("Tom has {a} apples and gets {b} more. How many apples does he have?",
     "{a} + {b} = {c}. Tom has {c} apples."),
    ("A train carries {a} people and picks up {b} more. How many people are on the train?",
     "{a} + {b} = {c}. There are {c} people on the train."),
    ("Mia read {a} pages yesterday and {b} pages today. How many pages in total?",
     "{a} + {b} = {c}. She read {c} pages in total."),
]
WORD_SUB = [
    ("Sam had {a} sweets and ate {b}. How many sweets are left?",
     "{a} - {b} = {c}. Sam has {c} sweets left."),
    ("A shop had {a} books and sold {b}. How many books remain?",
     "{a} - {b} = {c}. The shop has {c} books left."),
]
WORD_MUL = [
    ("There are {a} boxes with {b} pens in each box. How many pens in total?",
     "{a} times {b} = {c}. There are {c} pens in total."),
    ("A farmer has {a} rows of {b} trees. How many trees are there?",
     "{a} times {b} = {c}. There are {c} trees."),
]


def main(out_path: str = "my_ai/data/raw/math_synthetic.jsonl",
         n_samples: int = 4000, seed: int = 13) -> None:
    rng = random.Random(seed)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    rows = []
    for _ in range(n_samples):
        kind = rng.random()
        if kind < 0.30:                                    # addition
            a, b = rng.randint(0, 99), rng.randint(0, 99)
            q = rng.choice(Q_ADD).format(a=a, b=b)
            ans = f"{a} + {b} = {a + b}"
        elif kind < 0.55:                                  # subtraction (no negatives)
            a, b = rng.randint(0, 99), rng.randint(0, 99)
            a, b = max(a, b), min(a, b)
            q = rng.choice(Q_SUB).format(a=a, b=b)
            ans = f"{a} - {b} = {a - b}"
        elif kind < 0.75:                                  # multiplication tables
            a, b = rng.randint(0, 12), rng.randint(0, 12)
            q = rng.choice(Q_MUL).format(a=a, b=b)
            ans = f"{a} times {b} = {a * b}"
        elif kind < 0.85:                                  # exact division
            b = rng.randint(1, 12)
            c = rng.randint(0, 12)
            a = b * c
            q = rng.choice(Q_DIV).format(a=a, b=b)
            ans = f"{a} divided by {b} = {c}"
        else:                                              # word problems
            group = rng.choice([("add", WORD_ADD), ("sub", WORD_SUB), ("mul", WORD_MUL)])
            tpl_q, tpl_a = rng.choice(group[1])
            if group[0] == "add":
                a, b = rng.randint(1, 50), rng.randint(1, 50); c = a + b
            elif group[0] == "sub":
                a, b = rng.randint(10, 99), rng.randint(1, 9); c = a - b
            else:
                a, b = rng.randint(2, 9), rng.randint(2, 9); c = a * b
            q, ans = tpl_q.format(a=a, b=b), tpl_a.format(a=a, b=b, c=c)
        rows.append({"text": f"<|user|>{q}<eos><|assistant|>{ans}<eos>"})
    with open(out_path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"wrote {len(rows)} math samples to {out_path}")


if __name__ == "__main__":
    main()
